### ISSUE TITLE
Make interaction_responded a private variable.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [Goldy-Bot/Goldy-Bot-V5#30]
As the title says. Located over here: https://github.com/Goldy-Bot/Goldy-Bot-V5/blob/dev/buttons-implementation/GoldyBot/goldy/objects/golden_platter.py#L47

**Comment by THEGOLDENPRO** [comment]
Also make the reference to the send_msg function in the doc string an actual sphinx docs reference.

**Comment by Jambo199** [comment]
oi

**Comment by Jambo199** [comment]
oi oi

**Comment by Jambo199** [comment]
oi

**Comment by Jambo199** [comment]
oi

**Comment by THEGOLDENPRO** [comment]
fixed in v5.0dev2
