### ISSUE TITLE
Add database wrapper to docs

### ISSUE THREAD

**Issue by THEGOLDENPRO** [Goldy-Bot/Goldy-Bot-V5#64]
- [x] Add to docs
- [x] Adds examples of member database wrapper.
- [x] Add full example of member database wrapper.

**Comment by THEGOLDENPRO** [comment]
I need to do a full docs write soon anyways as everything has moved around.

**Comment by Aertic** [comment]
where can I access the docs????

**Comment by THEGOLDENPRO** [comment]
> where can I access the docs????
> 

Smh 🙄 it's literally linked as this repo's webpage: https://goldybot.devgoldy.xyz/

**Comment by THEGOLDENPRO** [comment]
closing as it has now been fixed in dev7
